export const AUTHENTICATED = "AUTHENTICATED";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const IS_LOADING = 'IS_LOADING';
export const LOGOUT = 'LOGOUT';
export const GET_USER_BY_ID__SUCCESS = 'GET_USER_BY_ID__SUCCESS'